# Generated by Django 5.1.5 on 2025-02-15 04:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contra', models.CharField(max_length=100)),
                ('fechaalta', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuenta.nivelaceeso')),
            ],
        ),
    ]
