# Generated by Django 5.1.5 on 2025-03-01 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_user'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuenta.user')),
            ],
        ),
    ]
