# Generated by Django 5.1.5 on 2025-03-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_billuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='concepto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='referencia',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
